version: 2.1

commands:
  configure-dockerhub:
    description: Configure Docker Hub access
    steps:
      - run:
          name: Configure Docker Hub
          command: |
            [ -z "$DOCKERHUB_USERNAME" ] && exit 0
            [ -z "$DOCKERHUB_TOKEN" ] && exit 0
            docker login --username $DOCKERHUB_USERNAME --password=$DOCKERHUB_TOKEN

jobs:
  build-amd64:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - configure-dockerhub
      - run:
          name: Build and push docker image for amd64
          command: cd images && make PLATFORMS=linux/amd64 TAG_SUFFIX=-amd64 GIT_TAG=<<pipeline.git.tag>> GIT_REVISION=<<pipeline.git.revision>>
  build-arm64:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - configure-dockerhub
      - run:
          name: Build and push docker image for arm64
          command: cd images && make PLATFORMS=linux/arm64 TAG_SUFFIX=-arm64 GIT_TAG=<<pipeline.git.tag>> GIT_REVISION=<<pipeline.git.revision>>
  push-multiarch-image:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - setup_remote_docker
      - configure-dockerhub
      - run:
          name: Create and push manifest for multiarch
          command: cd images && make push-manifest GIT_TAG=<<pipeline.git.tag>> GIT_REVISION=<<pipeline.git.revision>>
workflows:
  build-publish:
    jobs:
      - build-amd64:
          context: dockerhubsecret # the circleci context that contain your access token to dockerhub
          filters:
            tags:
              only: /.*/
      - build-arm64:
          context: dockerhubsecret
          filters:
            tags:
              only: /.*/
      - push-multiarch-image:
          context: dockerhubsecret
          requires:
            - build-arm64
            - build-amd64
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
