ARG ALPINE_VERSION=3.15
FROM alpine:${ALPINE_VERSION}
MAINTAINER Sam Wood <sam.wood@luthersystems.com>

RUN echo "nobody:x:1:1:nobody:/:/bin/sh" >> /etc/passwd
RUN echo "nobody:x:1:" >> /etc/group
RUN chmod 1777 /tmp
RUN apk --no-cache add libltdl tini ca-certificates
USER nobody
WORKDIR /opt
VOLUME ["/opt"]
ENTRYPOINT ["tini", "--"]
