ARG ALPINE_VERSION
FROM alpine:${ALPINE_VERSION}

RUN echo "nobody:x:1:1:nobody:/:/bin/sh" >> /etc/passwd
RUN echo "nobody:x:1:" >> /etc/group
RUN chmod 1777 /tmp
RUN apk --no-cache add libltdl tini ca-certificates
USER nobody
WORKDIR /opt
VOLUME ["/opt"]
ENTRYPOINT ["tini", "--"]
