ARG ALPINE_VERSION=3.15
FROM openjdk:19-jdk-alpine${ALPINE_VERSION}
MAINTAINER Sam Wood <sam.wood@luthersystems.com>

RUN echo "nobody:x:1:1:nobody:/:/bin/sh" >> /etc/passwd
RUN echo "nobody:x:1:" >> /etc/group
RUN chmod 1777 /tmp
RUN apk --no-cache add libltdl tini tzdata ca-certificates
USER nobody
WORKDIR /opt
VOLUME ["/opt"]
ARG BIN
ENV BIN ${BIN}
ADD target/${BIN} /opt/app.jar
ENTRYPOINT ["tini", "--", "java", "-jar", "/opt/app.jar"]
