FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY nginx/default.conf.template /etc/nginx/templates/
COPY nginx/nginx.conf /etc/nginx/nginx.conf

VOLUME ["/html"]

ENV NGINX_API_ENDPOINT=/v1/oracle \
  NGINX_API_ADDR=localhost \
  NGINX_AUTH_ENDPOINT=/v1/auth \
  NGINX_API_ADDR=localhost

EXPOSE 9090
