FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY nginx/nginx_serve.sh /opt/
COPY nginx/default.conf.template /etc/nginx/templates/
COPY nginx/nginx.conf /etc/nginx/nginx.conf

VOLUME ["/html"]

ENTRYPOINT ["sh", "/opt/nginx_serve.sh"]

EXPOSE 9090

CMD ["nginx", "-g", "daemon off;"]
