FROM ubuntu:22.04

RUN echo "nobody:x:1:1:nobody:/:/bin/sh" >> /etc/passwd
RUN echo "nobody:x:1:" >> /etc/group
RUN chmod 1777 /tmp
RUN apt-get update && apt-get install -y libltdl-dev tini ca-certificates && rm -rf /var/lib/apt/lists/*

USER nobody
WORKDIR /opt
VOLUME ["/opt"]
ARG BIN
ENV BIN ${BIN}
COPY build/bin/${BIN} /opt/app
ENTRYPOINT ["tini", "--", "/opt/app"]
