name: Build
on:
  pull_request:
    branches:
    - main
env:
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
jobs:
  build-amd64:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/configure-dockerhub"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64
    - name: Build and push docker image for amd64
      run: cd images && make PLATFORMS=linux/amd64 TAG_SUFFIX=-amd64 GIT_REVISION=$GITHUB_SHA
  build-arm64:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/configure-dockerhub"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm64
    - name: Build and push docker image for arm64
      run: cd images && make PLATFORMS=linux/arm64 TAG_SUFFIX=-arm64 GIT_REVISION=$GITHUB_SHA
