name: Build
on:
  pull_request:
    branches:
    - main
env:
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/configure-dockerhub"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/${{ matrix.arch }}
    - name: Build docker image for ${{ matrix.arch }}
      run: cd images && make PLATFORMS=linux/${{ matrix.arch }} TAG_SUFFIX=-${{ matrix.arch }} GIT_REVISION=$GITHUB_SHA
