name: Build docker images
on:
  pull_request:
    branches:
    - main
env:
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  build:
    name: Docker build ${{ matrix.image }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' ? 'buildjet-2vcpu-ubuntu-2204-arm' : 'ubuntu-20.04' }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        image:
          - build-go-alpine
          - service-base-alpine
          - build-api
          - build-swaggercodegen
          - multi-build-go
          - multi-build-goextra
          - multi-build-godynamic
          - multi-build-java
          - multi-build-js
    steps:
      - name: 'Build container'
        uses: ./.github/actions/build-docker-images
        with:
          arch: ${{ matrix.arch }}
          image: ${{ matrix.image }}
          git_rev: $GITHUB_SHA
