name: Build docker images
on:
  pull_request:
    branches:
      - main
env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  build:
    name: ${{ matrix.image }} - ${{ matrix.arch }} docker build
    runs-on: ${{ fromJSON('{"arm64":"buildjet-2vcpu-ubuntu-2204-arm","amd64":"ubuntu-22.04"}')[matrix.arch] }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        image:
          - build-go-alpine
          - service-base-alpine
          - nginx-frontend
          - build-api
          - build-swaggercodegen
          - multi-build-go
          - multi-build-godynamic
          - multi-build-java
          - multi-build-js
          - dynamodb-mcp-server
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        uses: ./.github/actions/build-docker-images
        with:
          arch: ${{ matrix.arch }}
          image: ${{ matrix.image }}
          git_rev: $GITHUB_SHA
