name: Build and Push
on:
  push:
    tags:
      - "*"
env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
jobs:
  build:
    name: ${{ matrix.image }} - ${{ matrix.arch }} docker build & push
    runs-on: ${{ fromJSON('{"arm64":"2vcpu-ubuntu-2204-arm","amd64":"ubuntu-22.04"}')[matrix.arch] }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        image:
          - build-api
          - build-go
          - build-go-alpine
          - build-godynamic
          - build-e2e
          - build-java
          - build-js
          - build-swaggercodegen
          - nginx-frontend
          - service-base-alpine
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Build & push container
        uses: ./.github/actions/build-docker-images
        with:
          arch: ${{ matrix.arch }}
          image: ${{ matrix.image }}
          git_tag: $GITHUB_REF_NAME

  push-manifests:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Configure DockerHub
        uses: ./.github/actions/configure-dockerhub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5  # v4
      - name: Create and push manifest for multiarch
        run: cd images && make push-manifests GIT_TAG=$GITHUB_REF_NAME
