name: Build and Push
on:
  push:
    tags:
    - '*'
env:
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
jobs:
  build-push:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
        image:
          - build-go-alpine
          - service-base-alpine
          - build-api
          - build-swaggercodegen
          - multi-build-go
          - multi-build-goextra
          - multi-build-godynamic
          - multi-build-java
          - multi-build-js
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/configure-dockerhub"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/${{ matrix.arch }}
    - name: Build and push docker image for ${{ matrix.arch }}
      run: cd images && make PLATFORMS=linux/${{ matrix.arch }} TAG_SUFFIX=-${{ matrix.arch }} GIT_TAG=$GITHUB_REF_NAME ${{ matrix.image }}
  push-manifests:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    needs:
    - build-push
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/configure-dockerhub"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Create and push manifest for multiarch
      run: cd images && make push-manifests GIT_TAG=$GITHUB_REF_NAME
