name: Build and Push
on:
  push:
    tags:
    - '*'
env:
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
jobs:
  build:
    name: Docker build & push ${{ matrix.image }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' ? 'buildjet-2vcpu-ubuntu-2204-arm' : 'ubuntu-20.04' }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        image:
          - build-go-alpine
          - service-base-alpine
          - build-api
          - build-swaggercodegen
          - multi-build-go
          - multi-build-goextra
          - multi-build-godynamic
          - multi-build-java
          - multi-build-js
    steps:
      - name: 'Build & push container'
        uses: ./.github/actions/build-docker-images
        with:
          arch: ${{ matrix.arch }}
          image: ${{ matrix.image }}
          git_tag: $GITHUB_REF_NAME

  push-manifests:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    needs:
    - build
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/configure-dockerhub"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Create and push manifest for multiarch
      run: cd images && make push-manifests GIT_TAG=$GITHUB_REF_NAME
